[workspace]
members = [
    "kernel",
    "xtask",
    "lib/libglenda-rs",
    "service/nineball",
    "service/factotum",
    "service/unicorn",
    "drivers/virtio/common",
    "drivers/virtio/block",
    "drivers/ns16550a",
    "examples/hello",
    "tests/ipc",
    "tests/cap",
    "tests/heap",
]
resolver = "2"


[profile.relwithdebuginfo]
inherits = "release"
debug = true         # 保留一些调试信息
