[workspace]
members = [
    "kernel",
    "xtask",
    "lib/libglenda-rs",
    "service/nineball",
    "service/factotum",
    "service/unicorn",
    "examples/dosbox",
    "drivers/virtio/common",
    "drivers/virtio/block",
    "drivers/ns16550a",
    "examples/hello",
    "tests/ipc",
    "tests/cap",
    "tests/heap",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.relwithdebuginfo]
panic = "abort"
inherits = "release"
lto = true           # 开启链接时优化，跨 crate 删除无用代码
codegen-units = 1    # 限制并行代码生成单元，有助于更好的全局优化
debug = true         # 保留一些调试信息
