[workspace]
members = [
    "kernel",
    "xtask",
    "lib/libape",
    "lib/libglenda-rs",
    "lib/libglenda_drivers-rs",
    "service/ape",
    "service/nineball",
    "service/warren",
    "service/unicorn",
    "examples/dosbox",
    "drivers/virtio/common",
    "drivers/virtio/block",
    "drivers/uart/ns16550a",
    "drivers/virtio/net",
    "drivers/timer/goldfish-rtc",
    "drivers/gpio/sifive-gpio",
    "drivers/sdio/sdhci",
    "fs/fatfs",
    "fs/extfs",
    "fs/initrdfs",
    "examples/hello",
    "service/gopher",
    "drivers/platform/acpi",
    "drivers/platform/dtb",
    "drivers/bus/pci",
    "drivers/virtio/mmio",
    "drivers/sys/ramdisk",
    "drivers/sys/loop",
    "service/fossil",
    "service/nexus",
    "service/march",
    "service/prism",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.development]
panic = "abort"
inherits = "dev"

[profile.relwithdebuginfo]
panic = "abort"
inherits = "release"
lto = true           # 开启链接时优化，跨 crate 删除无用代码
codegen-units = 1    # 限制并行代码生成单元，有助于更好的全局优化
debug = 2            # 保留一些调试信息
opt-level = 3        # 开启最高级别的优化
