[system]
arch = "riscv64"
profile = "relwithdebuginfo"
bootloader = "opensbi"

[qemu]
cpus = 4
mem = "2G"
display = "nographic"
disk = "./platform/qemu/alpine-linux-riscv64-ext4fs.img"
serial_port = 5555
net = true
mac = "52:54:00:11:22:33"
hostfwd = ["tcp::8088-:80"]

[[services]]
name = "warren"
path = "service/warren"
build = "cargo"
output = "build/warren.elf"
kind = "root_task"
[[services]]
name = "gopher"
path = "service/gopher"
build = "cargo"
output = "build/gopher.elf"
kind = "service"
[[services]]
name = "nineball"
path = "service/nineball"
build = "cargo"
output = "build/nineball.elf"
kind = "service"
[[services]]
name = "unicorn"
path = "service/unicorn"
build = "cargo"
output = "build/unicorn.elf"
kind = "service"
[[services]]
name = "nexus"
path = "service/nexus"
build = "cargo"
output = "build/nexus.elf"
kind = "service"
[[services]]
name = "factotum"
path = "service/factotum"
build = "cargo"
output = "build/factotum.elf"
kind = "service"
[[services]]
name = "chimera"
path = "service/chimera"
build = "cargo"
output = "build/chimera.elf"
kind = "service"
[[services]]
name = "prism"
path = "service/prism"
build = "cargo"
output = "build/prism.elf"
kind = "service"
[[services]]
name = "march"
path = "service/march"
build = "cargo"
output = "build/march.elf"
kind = "service"
[[services]]
name = "fossil"
path = "service/fossil"
build = "cargo"
output = "build/fossil.elf"
kind = "service"
[[services]]
name = "ape"
path = "service/ape"
build = "cargo"
output = "build/ape.elf"
kind = "service"
[[services]]
name = "libape_daemon"
path = "lib/libape"
build = "cargo"
output = "build/libape_daemon.elf"
kind = "service"

[[services]]
name = "initrdfs"
path = "fs/initrdfs"
build = "cargo"
output = "build/initrdfs.elf"
kind = "driver"
[[services]]
name = "loop"
path = "drivers/sys/loop"
build = "cargo"
output = "build/loop.elf"
kind = "driver"
[[services]]
name = "fatfs"
path = "fs/fatfs"
build = "cargo"
output = "build/fatfs.elf"
kind = "driver"
[[services]]
name = "extfs"
path = "fs/extfs"
build = "cargo"
output = "build/extfs.elf"
kind = "driver"
[[services]]
name = "ns16550a"
path = "drivers/uart/ns16550a"
build = "cargo"
output = "build/ns16550a.elf"
kind = "driver"
[[services]]
name = "virtio-blk"
path = "drivers/virtio/block"
build = "cargo"
output = "build/virtio-blk.elf"
kind = "driver"
[[services]]
name = "virtio-net"
path = "drivers/virtio/net"
build = "cargo"
output = "build/virtio-net.elf"
kind = "driver"
[[services]]
name = "virtio-gpu"
path = "drivers/virtio/gpu"
build = "cargo"
output = "build/virtio-gpu.elf"
kind = "driver"
[[services]]
name = "goldfish-rtc"
path = "drivers/timer/goldfish-rtc"
build = "cargo"
output = "build/goldfish-rtc.elf"
kind = "driver"
[[services]]
name = "dtb"
path = "drivers/platform/dtb"
build = "cargo"
output = "build/dtb.elf"
kind = "driver"
[[services]]
name = "pci"
path = "drivers/bus/pci"
build = "cargo"
output = "build/pci.elf"
kind = "driver"
[[services]]
name = "virtio-mmio"
path = "drivers/virtio/mmio"
build = "cargo"
output = "build/virtio-mmio.elf"
kind = "driver"
[[services]]
name = "ramdisk"
path = "drivers/sys/ramdisk"
build = "cargo"
output = "build/ramdisk.elf"
kind = "driver"

[[services]]
name = "hello"
path = "examples/hello"
build = "cargo"
output = "build/hello.elf"
kind = "test"

[[files]]
name = "init.json"
path = "config/init.json"
[[files]]
name = "drivers.json"
path = "config/drivers.json"
[[files]]
name = "fs.json"
path = "config/fs.json"
[[files]]
name = "network.json"
path = "config/network.json"
[[files]]
name = "tty.json"
path = "config/tty.json"
[[files]]
name = "ape.json"
path = "config/ape.json"

[features]
kernel = ["initrd-embed"]
libglenda-rs = ["rt-bare"]
libape = ["runtime"]
musl-glenda = ["--disable-shared", "--prefix=../../target/sysroot"]
ape = ["strace"]
