[system]
arch = "riscv64"
profile = "relwithdebuginfo"
bootloader = "opensbi"

[qemu]
cpus = 1
mem = "2G"
display = "nographic"
drive = "disk.img"
net = true
mac = "52:54:00:11:22:33"
hostfwd = ["tcp::8080-:80"]

[[services]]
name = "warren"
path = "service/warren"
build = "cargo"
output = "build/warren.elf"
kind = "root_task"
[[services]]
name = "nineball"
path = "service/nineball"
build = "cargo"
output = "build/nineball.elf"
kind = "service"
[[services]]
name = "unicorn"
path = "service/unicorn"
build = "cargo"
output = "build/unicorn.elf"
kind = "service"
[[services]]
name = "ns16550a"
path = "drivers/uart/ns16550a"
build = "cargo"
output = "build/ns16550a.elf"
kind = "service"
[[services]]
name = "virtio-blk"
path = "drivers/virtio/block"
build = "cargo"
output = "build/virtio-blk.elf"
kind = "service"
[[services]]
name = "goldfish-rtc"
path = "drivers/timer/goldfish-rtc"
build = "cargo"
output = "build/goldfish-rtc.elf"
kind = "service"
[[services]]
name = "virtio-net"
path = "drivers/virtio/net"
build = "cargo"
output = "build/virtio-net.elf"
kind = "service"
[[services]]
name = "dtb"
path = "drivers/platform/dtb"
build = "cargo"
output = "build/dtb.elf"
kind = "service"
[[services]]
name = "virtio-mmio"
path = "drivers/virtio/mmio"
build = "cargo"
output = "build/virtio-mmio.elf"
kind = "service"
[[services]]
name = "acpi"
path = "drivers/platform/acpi"
build = "cargo"
output = "build/acpi.elf"
kind = "service"

[[libraries]]
name = "libglenda-rs"
path = "lib/libglenda-rs"
build = "cargo"
output = ""

[[files]]
name = "init.json"
path = "platform/qemu/init.json"
[[files]]
name = "drivers.json"
path = "platform/qemu/drivers.json"
[[files]]
name = "fs.json"
path = "platform/qemu/fs.json"

[features]
kernel = []
libglenda-rs = ["rt-bare"]
musl-glenda = ["--disable-shared", "--prefix=../../target"]
