fn main() {
    println!("cargo:rerun-if-changed=src/boot.S");
    println!("cargo:rerun-if-changed=src/trap/vector.S");
    println!("cargo:rerun-if-changed=src/init/sbi.S");
    println!("cargo:rerun-if-changed=src/proc/enter.S");
    println!("cargo:rerun-if-changed=src/proc/switch.S");
    println!("cargo:rerun-if-changed=src/hart_tp.S");
    println!("cargo:rerun-if-changed=src/linker.ld");
    cc::Build::new()
        .file("src/boot.S")
        .file("src/trap/vector.S")
        .file("src/init/sbi.S")
        .file("src/proc/enter.S")
        .file("src/proc/switch.S")
        .file("src/hart_tp.S")
        .flag("-march=rv64gc")
        .flag("-mabi=lp64d")
        .compile("boot");
}
