[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
acpi = { version = "6.1.0", default-features = false }
bitflags = "2.10.0"
fdt = "0.1.5"
limine = "0.5.0"
num_enum = { version = "0.7.5", default-features = false }

[build-dependencies]
chrono = "0.4"

[features]
default = ["logging", "bl-limine"]
logging = []
shell = []
gdb = []
bl-limine = []
bl-multiboot2 = []
bl-uefi = []
bl-opensbi = []
