[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
acpi = { version = "6.1.0", default-features = false }
bitflags = "2.10.0"
fdt = "0.1.5"
limine = { version = "0.5.0", optional = true }
multiboot2 = { version = "0.22.0", default-features = false, optional = true }
uefi = { version = "0.33.0", default-features = false, optional = true }
num_enum = { version = "0.7.5", default-features = false }
font8x8 = { version = "0.3.1", default-features = false, features = [
    "unicode",
] }

[build-dependencies]
chrono = "0.4"

[features]
default = ["logging"]
logging = []
shell = []
embed-initrd = []
bl-limine = ["limine"]
bl-uboot = []
bl-multiboot2 = ["multiboot2"]
bl-uefi = ["uefi"]
bl-linuxboot = []
