[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C","link-arg=-Tkernel/src/linker.ld",
  "-C","link-arg=--gc-sections",
]

[target.riscv64gc-unknown-none-elf.bin]
kernel = "qemu-system-riscv64 -machine virt -m 128M -bios default -nographic -kernel"
