[system]
arch = "riscv64"
profile = "release"

[qemu]
cpus = 1
mem = "1G"
display = "nographic"
bootargs = "-s"

# Root Task: DOSBox Emulator
[[services]]
name = "dosbox"
path = "examples/dosbox"
build = "cargo"
output = "build/dosbox"
kind = "root_task"

# Floppy Image
[[services]]
name = "pcdos330.img"
path = "examples/dosbox/images"
output = "PCDOS330.img"
build = "manifest"
kind = "file"

[[libraries]]
name = "libglenda-rs"
path = "lib/libglenda-rs"
build = "cargo"
[features]
kernel = []
libglenda-rs = ["rt-bare"]
