[system]
arch = "riscv64"
profile = "release"

[qemu]
cpus = 1
mem = "1G"
display = "nographic"
bootargs = "-s"

# Root Task: DOSBox Emulator
[[services]]
name = "dosbox"
path = "examples/dosbox"
build = "cargo"
output = "build/dosbox"
kind = "root_task"

[[files]]
name = "init.json"
path = "config/init.json"

[[files]]
name = "pcdos330.img"
path = "examples/dosbox/images/PCDOS330.img"

[[libraries]]
name = "libglenda-rs"
path = "lib/libglenda-rs"
build = "cargo"
[features]
kernel = []
libglenda-rs = ["rt-bare"]
