[system]
arch = "riscv64"
profile = "relwithdebuginfo"
bootloader = "linuxboot"

[qemu]
cpus = 1
mem = "1G"
display = "nographic"
bootargs = "-s"

[[services]]
name = "hello"
path = "examples/hello"
build = "cargo"
output = "build/hello.elf"
kind = "root_task"
[features]
kernel = []
libglenda-rs = ["rt-bare"]
